# Generated by Django 4.2.7 on 2023-11-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('abia_gis_fileno', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_allotee', models.CharField(max_length=100)),
                ('name_of_surveyor', models.CharField(blank=True, max_length=100, null=True)),
                ('landuse', models.CharField(blank=True, max_length=100, null=True)),
                ('spacial_lga', models.CharField(blank=True, max_length=100, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.CharField(max_length=100)),
                ('line_length', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=50)),
                ('internal_angle', models.CharField(max_length=30)),
                ('from_beacon_no', models.CharField(max_length=100)),
                ('to_beacon_no', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('parcelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedBackCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Generated', models.BooleanField(default=False)),
                ('Generated_by', models.CharField(max_length=100)),
                ('Generated_date', models.DateField(blank=True, null=True)),
                ('FileNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.parcel')),
            ],
        ),
    ]
