# Generated by Django 4.2.7 on 2023-11-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('OBJECTID', models.CharField(max_length=100)),
                ('FileNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_of_Allottee', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_of_Surveyor', models.CharField(blank=True, max_length=100, null=True)),
                ('Landuse', models.CharField(blank=True, max_length=100, null=True)),
                ('LGA', models.CharField(blank=True, max_length=100, null=True)),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Plan_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Plot_No', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Particulars', models.CharField(blank=True, max_length=100, null=True)),
                ('Starting_Pillar_No', models.CharField(blank=True, max_length=100, null=True)),
                ('StatedArea', models.CharField(blank=True, max_length=100, null=True)),
                ('Picture', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.CharField(blank=True, max_length=100, null=True)),
                ('Length', models.CharField(blank=True, max_length=100, null=True)),
                ('Sequence', models.CharField(blank=True, max_length=50, null=True)),
                ('InternalAngle', models.CharField(blank=True, max_length=30, null=True)),
                ('FromBeaconNo', models.CharField(blank=True, max_length=100, null=True)),
                ('ToBeaconNo', models.CharField(blank=True, max_length=100, null=True)),
                ('Direction', models.CharField(blank=True, max_length=100, null=True)),
                ('Northings', models.CharField(blank=True, max_length=100, null=True)),
                ('Eastings', models.CharField(blank=True, max_length=100, null=True)),
                ('ParcelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.parcel')),
            ],
        ),
    ]
