# Generated by Django 4.2.7 on 2023-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='Name_of_Allottee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
