# Generated by Django 4.2.7 on 2023-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0002_alter_lines_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='Dir1',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='lines',
            name='Dir2',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
